# Generated by Django 4.0.3 on 2022-04-02 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appel_ei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
